# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BestBar' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BestBar
  pod 'Firebase'
  pod 'Firebase/Firestore'
  pod 'Cosmos', '~> 20.0'
  pod 'Nuke', '~> 8.0'
  pod 'SKPhotoBrowser'
  pod 'lottie-ios'
end
